ebdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('forecast/', include('forecast.urls')),
    path('admin/', admin.site.urls),
]

forecast/urls.py
from django.urls import path

from . import views

app_name = 'forecast'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /forecast/
    path('<int:query_id>/', views.detail, name='detail'),
    # ex: /forecast/5/
    path('<int:query_id>/<str:run_estimation_response>', views.detail, name='detail'),
    # ex: /forecast/5/message
    path('<int:query_id>/results/<int:estimation_id>/', views.results, name='results'),
    # ex: /forecast/5/results/2
    path('<int:query_id>/run-estimation/', views.run_estimation, name='run_estimation'),
    # ex: /forecast/5/create-form/
    path('create-query/', views.create_query, name='create_query'),
    # ex: /forecast/create-query/
    path('<int:query_id>/delete-estimation/<int:estimation_id>/', views.delete_estimation, name='delete_estimation'),
    # ex: /forecast/5/delete-estimation/2
    path('delete-query/<int:query_id>/', views.delete_query, name='delete_query')
    # ex: /forecast/delete-query/5
]

forecast/models.py
from numpy import random, ceil

from django.db import models
from django.utils import timezone

from forecast.helperMethods.forecast_utils import parse_durations_for_ui, list_of_primitives_as_string

WEEK_IN_DAYS = 7
SUCCESS_MESSAGE = "succeeded"


class EstimationInput(models.Model):
    creation_date = models.DateTimeField(default=timezone.now)

    wip_lower_bound = models.PositiveSmallIntegerField(default=20)
    wip_upper_bound = models.PositiveSmallIntegerField(default=30)

    wip_filter = models.TextField(default="")

    throughput_lower_bound = models.FloatField(default=1.00)
    throughput_upper_bound = models.FloatField(default=5.00)

    throughput_filter = models.TextField(default="")

    split_rate_wip = models.FloatField(default=0.5)
    split_rate_throughput = models.FloatField(default=0.7)

    simulation_count = models.PositiveSmallIntegerField(default=1000000)

    class Meta:
        abstract = True


class Query(models.Model):
    name = models.CharField(max_length=200)

    description = models.CharField(max_length=200, default='N/A')

    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def run_estimation(self):
        form = self.form

        run_estimation_response = form.check_validity()

        if run_estimation_response != SUCCESS_MESSAGE:
            return run_estimation_response

        wip = random.uniform(form.wip_lower_bound, form.wip_upper_bound,
                             (form.simulation_count,))

        weekly_throughput = random.uniform(form.throughput_lower_bound, form.throughput_upper_bound,
                                           (form.simulation_count,))

        completion_duration = (ceil(wip / weekly_throughput)).astype(int)

        durations = list_of_primitives_as_string(completion_duration)

        centile_values, weeks, weeks_frequency, point_radius_list, point_color_list \
            = parse_durations_for_ui(completion_duration)

        # Create new Estimation
        self.estimation_set\
            .create(query=self,
                    durations=durations,
                    wip_lower_bound=form.wip_lower_bound,
                    wip_upper_bound=form.wip_upper_bound,
                    wip_filter=form.wip_filter,
                    throughput_lower_bound=form.throughput_lower_bound,
                    throughput_upper_bound=form.throughput_upper_bound,
                    throughput_filter=form.throughput_filter,
                    simulation_count=form.simulation_count,
                    centile_values=list_of_primitives_as_string(centile_values),
                    weeks=list_of_primitives_as_string(weeks),
                    weeks_frequency=list_of_primitives_as_string(weeks_frequency),
                    point_radius_list=list_of_primitives_as_string(point_radius_list),
                    point_color_list=list_of_primitives_as_string(point_color_list))

        return run_estimation_response


class Form(EstimationInput):
    query = models.OneToOneField(Query, on_delete=models.CASCADE, primary_key=True)

    def check_validity(self):
        run_estimation_response = ""

        if 0 > self.wip_lower_bound or self.wip_lower_bound > self.wip_upper_bound:
            run_estimation_response += f"WIP is " \
                f"({self.wip_lower_bound}, {self.wip_upper_bound}). "

        if 0 >= self.throughput_lower_bound or self.throughput_lower_bound > self.throughput_upper_bound:
            run_estimation_response += f"Throughput is " \
                f"({self.throughput_lower_bound}, { self.throughput_upper_bound}). "

        if 0 > self.split_rate_wip or self.split_rate_wip > 1.00:
            run_estimation_response += f"Split Rate for WIP is " \
                f"{self.split_rate_wip}. "

        if 0 > self.split_rate_throughput or self.split_rate_throughput > 1.00:
            run_estimation_response += f"Split Rate for Throughput is " \
                f"{self.split_rate_throughput}. "

        return f"failed: {run_estimation_response}" if run_estimation_response else SUCCESS_MESSAGE


class Estimation(EstimationInput):
    query = models.ForeignKey(Query, on_delete=models.CASCADE)

    durations = models.TextField()

    centile_values = models.TextField()
    weeks = models.TextField()
    weeks_frequency = models.TextField()
    point_radius_list = models.TextField()
    point_color_list = models.TextField()

forecast/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from forecast.helperMethods.rest import fetch_filters_and_update_form
from forecast.helperMethods.forecast_utils import remove_order_by_from_filter, \
    append_resolution_to_form_filters, dispatch_estimation_ui_values, compute_latest_estimations_change_table
from .models import Query, Estimation, Form


def index(request):
    query_list = Query.objects.order_by('-creation_date')

    context = {
        'nbar': 'index',
        'query_list': query_list}

    return render(request, 'forecast/index.html', context)


def detail(request, query_id, run_estimation_response=None):
    query = get_object_or_404(Query, pk=query_id)

    initial_wip, initial_throughput = fetch_filters_and_update_form(query.form)

    latest_estimation_list = query.estimation_set.order_by('-creation_date')

    latest_estimation = latest_estimation_list.first()

    weeks_frequency_sum = \
        latest_estimation.simulation_count \
        if latest_estimation_list.exists() \
        else None

    (centile_values, weeks, weeks_frequency,
      point_radius_list, point_color_list) = \
        dispatch_estimation_ui_values(latest_estimation) \
        if latest_estimation_list.exists() \
        else ([], [], [], [], [])

    latest_estimation_change_table = \
        compute_latest_estimations_change_table(query.estimation_set.order_by('creation_date'))

    context = {
        'nbar': 'detail',
        'query': query,
        'form': query.form,
        'run_estimation_response': run_estimation_response,
        'initial_wip': initial_wip,
        'initial_throughput': initial_throughput,
        'latest_estimation_list': latest_estimation_list,
        'centile_indices': [5*i for i in range(0, 21)],
        'centile_values': centile_values,
        'weeks': weeks,
        'weeks_frequency': weeks_frequency,
        'weeks_frequency_sum': ("SAMPLE SIZE: " + str(weeks_frequency_sum)),
        'point_radius_list': point_radius_list,
        'point_color_list': point_color_list,
        'latest_estimation_change_table': latest_estimation_change_table}

    return render(request, 'forecast/detail.html', context)


def results(request, query_id, estimation_id):
    query = get_object_or_404(Query, pk=query_id)

    estimation = get_object_or_404(Estimation, pk=estimation_id)

    (centile_values, weeks, weeks_frequency, point_radius_list, point_color_list) = \
        dispatch_estimation_ui_values(estimation)

    context = {
        'nbar': 'results',
        'centile_indices': [5*i for i in range(0, 21)],
        'centile_values': centile_values,
        'query': query,
        'weeks': weeks,
        'weeks_frequency': weeks_frequency,
        'weeks_frequency_sum': ("SAMPLE SIZE: " + str(estimation.simulation_count)),
        'point_radius_list': point_radius_list,
        'point_color_list': point_color_list}

    return render(request, 'forecast/results.html', context)


def run_estimation(request, query_id):

    Form.objects \
        .filter(query__pk=query_id) \
        .update(wip_lower_bound=int(request.POST['wip_lower_bound']),
                wip_upper_bound=int(request.POST['wip_upper_bound']),
                wip_filter=remove_order_by_from_filter(request.POST['wip_filter']),
                throughput_lower_bound=float(request.POST['throughput_lower_bound']),
                throughput_upper_bound=float(request.POST['throughput_upper_bound']),
                throughput_filter=remove_order_by_from_filter(request.POST['throughput_filter']),
                split_rate_wip=float(request.POST['split_rate_wip']),
                split_rate_throughput=float(request.POST['split_rate_throughput']))

    query = get_object_or_404(Query, pk=query_id)

    run_estimation_response = query.run_estimation()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('forecast:detail', args=(query_id, run_estimation_response,)))


def create_query(request):
    query = Query(name=request.POST['name'], description=request.POST['description'])

    query.save()

    wip_filter, throughput_filter = append_resolution_to_form_filters(
        remove_order_by_from_filter(request.POST['filter']))

    Form.objects.create(query=query,
                        wip_filter=wip_filter,
                        throughput_filter=throughput_filter)

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('forecast:index'))


def delete_estimation(request, query_id, estimation_id):
    estimation = get_object_or_404(Estimation, pk=estimation_id)
    estimation.delete()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('forecast:detail', args=(query_id,)))


def delete_query(request, query_id):
    query = get_object_or_404(Query, pk=query_id)
    query.delete()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('forecast:index'))

forecast/templates/forecast/index.html
{% extends "base.html" %}
{% block title %}My amazing index{% endblock %}

{% block body %}
    <br>
    <h1 class="text-center" >Choose Query - Total number of Queries in database: {{query_list.count}} </h1>
    <br>
    <div id="accordion">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-light btn-lg btn-block" data-toggle="collapse"
                            data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <b> Create Query </b>
                    </button>
                </h5>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                 data-parent="#accordion" style="background-color: rgb(240, 240, 240);">
                <div class="card-body">
                    <div class="container">
                        <form action="{% url 'forecast:create_query' %}" method="post">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="name"> <b> Name </b></label>
                                    <input type="text" name="name" class="form-control" id="name" value="My Query">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="description"> <b> Description </b> </label>
                                    <input type="text" name="description" class="form-control" id="description" value="abcdefgh">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="filter"> <b> JQL Filter </b></label>
                                    <input type="text" name="filter" class="form-control" id="filter" value="">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <input type="submit" name="create-button_jql" class="form-control btn btn-success" id="create-button_jql" value="->"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <input class="form-control" id="myInput" type="text" placeholder="Search query by keyword...">
    <br>
    <table class="table table-bordered table-striped" style="table-layout: fixed;word-wrap: break-word">
        <thead>
        <tr>
            <th>Inspect Query</th>
            <th>Delete Query</th>
            <th>Query Name</th>
            <th>Query Description</th>
            <th>Query WIP Filter</th>
            <th>Query Throughput Filter</th>
        </tr>
        </thead>
        <tbody id="myTable">
        {% for query in query_list %}
        <tr>
            <td>
                <form action="{% url 'forecast:detail' query.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="supporttype"/>
                    <input class="btn btn-success" type="submit" value="->">
                </form>
            </td>
            <td>
                <form action="{% url 'forecast:delete_query' query.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="supporttype"/>
                    <input class="btn btn-danger" type="submit" value="X">
                </form>
            </td>
            <td>
                {{ query.name }}
            </td>
            <td>
                {{ query.description }}
            </td>
            <td>
                {{ query.form.wip_filter }}
            </td>
            <td>
                {{ query.form.throughput_filter }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block body_scripts %}
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

forecast/templates/forecast/results.html
{% extends "base.html" %}
{% block title %}My amazing results{% endblock %}

{% block body %}

    <canvas id="myProbabilityDistribution"></canvas>

    {{ weeks |json_script:"weeks"}}
    {{ weeks_frequency |json_script:"weeks_frequency"}}
    {{ weeks_frequency_sum |json_script:"weeks_frequency_sum"}}
    {{ centile_values |json_script:"centile_values"}}
    {{ point_radius_list |json_script:"point_radius_list"}}
    {{ point_color_list |json_script:"point_color_list"}}

{% endblock %}

{% block body_scripts %}
<script>
    var ctx = document.getElementById('myProbabilityDistribution').getContext('2d');
    var weeks = JSON.parse(document.getElementById('weeks').textContent);
    var weeks_frequency = JSON.parse(document.getElementById('weeks_frequency').textContent);
    var weeks_frequency_sum = JSON.parse(document.getElementById('weeks_frequency_sum').textContent);
    var centile_values = JSON.parse(document.getElementById('centile_values').textContent);
    var point_radius_list = JSON.parse(document.getElementById('point_radius_list').textContent);
    var point_color_list = JSON.parse(document.getElementById('point_color_list').textContent);

    var gradientStroke = ctx.createLinearGradient(0, 0, $(window).width(), 0);
    gradientStroke.addColorStop(0, "rgba(244,29,49,0.6)");
    gradientStroke.addColorStop(0.5, "rgba(244,215,28,0.6)");
    gradientStroke.addColorStop(1, "rgba(120,244,31,0.6)");

    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',
        // The data for our dataset
        data: {
            labels: weeks,
            datasets: [{
                label: weeks_frequency_sum,
                pointBorderColor: point_color_list,
                pointBorderWidth: 10,
                pointHoverRadius: point_radius_list,
                pointHoverBorderWidth: 10,
                pointRadius: point_radius_list,
                fill: true,
                // borderColor: gradientStroke,
                // pointBackgroundColor: gradientStroke,
                // pointHoverBackgroundColor: gradientStroke,
                // pointHoverBorderColor: gradientStroke,
                // backgroundColor: gradientStroke,
                borderWidth: 4,
                data: weeks_frequency
            }]
        },

        // Configuration options go here
        options: {
            title: {
                display: true,
                text: 'Estimation Results - Discrete Probability Distribution'
            },
            scales: {
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: 'Probability'
                    },
                    gridLines: {
                        display:false
                    }
                }],
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: 'Week'
                    },
                    ticks: {
                        userCallback: function(item, index) {
                            if (centile_values.indexOf(parseInt(item,10)) > -1) return item;
                        },
                        autoSkip: false
                    },
                    gridLines: {
                        userCallback: function(item, index) {
                            console.log((centile_values.indexOf(parseInt(item,10)) > -1));
                            if (centile_values.indexOf(parseInt(item,10)) > -1) return item;
                        },
                        autoSkip: false
                    }
                }]
            },
            tooltips: {
                mode: 'nearest',
                filter: function (item, data) {
                    return item.label !== "undefined";

                },
                callbacks: {
                    label: function(tooltipItem, data) {
                        var firstIndexOfItem = ((centile_values.indexOf(parseInt(tooltipItem.xLabel))) * 5).toString();
                        var lastIndexOfItem = ((centile_values.lastIndexOf(parseInt(tooltipItem.xLabel))) * 5).toString();
                        if (firstIndexOfItem === lastIndexOfItem)
                        {return firstIndexOfItem.concat(" % LIKELIHOOD")}
                        else
                        {return firstIndexOfItem.concat(" - ", lastIndexOfItem, " % LIKELIHOOD")}
                    }
                }
            }
        },
        plugins: [{
            beforeRender: function (x, options) {
                var c = x.chart;
                var dataset = x.data.datasets[0];

                var fille = ctx.createLinearGradient(0, 0, c.width, 0);
                fille.addColorStop(0, "rgba(244,29,49,0.6)");
                fille.addColorStop(0.3, "rgba(244,215,28,0.6)");
                fille.addColorStop(1, "rgba(120,244,31,0.6)");

                var model = x.data.datasets[0]._meta[Object.keys(dataset._meta)[0]].dataset._model;
                model.backgroundColor = fille;
                model.pointBackgroundColor= fille;
                model.pointHoverBackgroundColor= fille;
                model.pointHoverBorderColor = fille;
                model.borderColor = fille;
            }
        }]
    });
</script>

{% endblock %}